Update docs add pause_at_block
AntelopeIO/spring pull request #1088
Opened 2024-12-31 07:43 UTC by ericpassmore

Add documentation for new plugin producer method. Available for review on staging https://staging.docs.eosnetwork.com/apis/spring/latest/producer.api#operation/pause_at_block

Resolves #1087 
Related to PR #1056

![Screenshot 2024-12-31 at 3 35 06 PM](https://github.com/user-attachments/assets/1fe4585d-d778-49ae-bf6c-5c1bdbd1fe04)

2025-01-02 13:06 UTC, heifner requested changes

2025-01-02 13:06 UTC, heifner commented on plugins/producer_api_plugin/producer.swagger.yaml
> +      description: Pause producer node at the specified block.
Something more like: "Pause node at the specified block. Use /producer/resume to un-pause. If specified block is less than head then returns an error."

Note that is pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rolls of a table. This would allow the user to freeze at a block number and then iterate through an entire table.

2025-01-02 21:24 UTC, heifner commented on plugins/producer_api_plugin/producer.swagger.yaml
> +      Note that is pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rolls o
s/Note that is pauses/Note that this pauses/

2025-01-02 21:33 UTC, greg7mdp commented on plugins/producer_api_plugin/producer.swagger.yaml
> +      Note that is pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rolls o
s/rolls/rows/

2025-01-02 21:59 UTC, greg7mdp commented on plugins/producer_api_plugin/producer.swagger.yaml
> +        ### Useage
```suggestion
        ### Usage
```

2025-01-02 22:44 UTC, ericpassmore commented
Updated, took a bit to figure out how to do multi-line descriptions. 
![Screenshot 2025-01-03 at 6 42 59 AM](https://github.com/user-attachments/assets/4bf1d979-4ea2-4aed-a3cc-f7c7a2e41ebb)

2025-01-02 22:47 UTC, ericpassmore commented
Note:start
category: Documentation
component: API
summary: Add documentation for new API pause_at_block
Note:end

2025-01-02 23:14 UTC, greg7mdp requested changes

2025-01-02 23:14 UTC, greg7mdp commented on plugins/producer_api_plugin/producer.swagger.yaml
> +        Note that this pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rol
I think it should be `rows`.
```suggestion
        Note that this pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rows of a table. This would allow the user to freeze at a block number and then iterate through an entire table.
```

2025-01-04 00:40 UTC, ericpassmore commented on plugins/producer_api_plugin/producer.swagger.yaml
> +        Note that this pauses all nodes not just producer nodes. The common use case is to use on non-producer nodes as a way of freezing state. For example, a user might wish to download all the rol
ha!

2025-01-04 03:54 UTC, greg7mdp approved these changes

2025-01-04 04:02 UTC, ericpassmore commented
![Screenshot 2025-01-04 at 12 01 13 PM](https://github.com/user-attachments/assets/8096a1d7-afc5-4760-9166-6b230a6cf13c)

2025-01-04 14:50 UTC, heifner approved these changes

2025-01-06 20:25 UTC, heifner approved these changes

2025-01-06 20:47 UTC, ericpassmore commented
Note: Changed PR to merge from main into existing Draft PR. Force push effective rebase to new target with docs changes approved in this PR.

2025-01-06 21:27 UTC, merged