Add a SHiP test to verify `get_blocks_result_v1` works across Legacy and Savanna boundary
AntelopeIO/spring pull request #114
Opened 2024-05-06 17:35 UTC by linh2931

This test verifies SHiP `get_blocks_result_v1` works across Legacy and Savanna boundary.

In particular, the test sends a `get_blocks_result_v1` requesting blocks between block number 1 (pre Savanna) and a block whose block number greater than Savanna Genesis block (post Savanna). It then  verifies `finality_data` field in every block before Savanna Genesis block is NULL, `finality_data` field in every block after Savanna Genesis block contains a value.

Resolves https://github.com/AntelopeIO/spring/issues/111

2024-05-06 18:23 UTC, heifner requested changes

2024-05-06 19:12 UTC, heifner approved these changes

2024-05-06 22:05 UTC, ericpassmore commented
Note:start
group: IF
category: TEST
summary: Ass Ship test to verify get_block_result_v1 works across both Legacy and Savanna finality modes.
Note:end

2024-05-06 22:38 UTC, greg7mdp approved these changes

2024-05-06 22:38 UTC, greg7mdp commented on tests/ship_reqs_across_svnn_test.py
> +    cluster.waitOnClusterSync(blockAdvancing=3)
Why call `waitOnClusterSync` twice?

2024-05-06 22:38 UTC, greg7mdp commented on tests/ship_reqs_across_svnn_test.py
> +    end_block_num = start_block_num + shipNode.getBlockNum()
why `start_block_num + `?

2024-05-07 00:05 UTC, linh2931 commented on tests/ship_reqs_across_svnn_test.py
> +    end_block_num = start_block_num + shipNode.getBlockNum()
Thanks!

2024-05-07 00:54 UTC, greg7mdp approved these changes

2024-05-07 01:02 UTC, merged