Make unit tests run in both Legacy and Savanna (Part 2, api_tests)
AntelopeIO/spring pull request #157
Opened 2024-05-17 15:58 UTC by linh2931

Continuing the effort to  make unit tests run in both Legacy and Savanna modes
 * Further enhance Libtester to support more scenarios in running tests in both Legacy and Savanna
 * Update `api_tests` to run in both Legacy and Savanna modes
 * Move finality related tests out from `api_tests.cpp` to `finality_tests.cpp` for better modularity

Note: `light_validation_skip_cfa` was not made to run in Savanna as it failed to run. https://github.com/AntelopeIO/spring/issues/156 was created to track it.

Partially resolves https://github.com/AntelopeIO/spring/issues/11

2024-05-17 16:53 UTC, ericpassmore commented
Note:start
group: IF
category: TEST
summary: Run unit tests in both Legacy DPOS and Savanna Consensus Modes, part 2.
Note:end

2024-05-17 17:10 UTC, heifner requested changes

2024-05-17 17:10 UTC, heifner commented on unittests/api_tests.cpp
> +   this->produce_blocks(2);
Personally, I prefer the approach used in the prior PR:
```
BOOST_AUTO_TEST_CASE_TEMPLATE( missing_sigs, TESTER, validating_testers ) { try {
   TESTER chain;
```
Over using the less documented `BOOST_FIXTURE_TEST_CASE_TEMPLATE` and having `this->`. To me `chain.` is better than `this->`. 

I'm also concerned about `BOOST_AUTO_TEST_CASE_TEMPLATE` not being maintained by Boost.

2024-05-17 20:05 UTC, heifner approved these changes

2024-05-18 02:25 UTC, spoonincode approved these changes

2024-05-18 14:39 UTC, merged