Test: P2P throttle test: Wait for begin block before measuring sync
AntelopeIO/spring pull request #329
Opened 2024-06-27 20:09 UTC by heifner

Before measuring the throttled node sync throttling make sure it has the begin block.

Resolves #326

2024-06-27 20:37 UTC, greg7mdp requested changes
This will be executed only if __debug__ is true. Is this always the case?
see [this](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)

2024-06-27 20:39 UTC, heifner commented
> This will be executed only if **debug** is true. Is this always the case? see [this](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement)

> variable [__debug__](https://docs.python.org/3/library/constants.html#debug__) is True under normal circumstances, False when optimization is requested (command line option [-O](https://docs.python.org/3/using/cmdline.html#cmdoption-O))

2024-06-27 20:55 UTC, linh2931 approved these changes

2024-06-27 21:42 UTC, greg7mdp commented
> variable [**debug**](https://docs.python.org/3/library/constants.html#debug__) is True under normal circumstances, False when optimization is requested (command line option [-O](https://docs.python.org/3/using/cmdline.html#cmdoption-O))

So we probably shouldn't use assert as the wait will not be executed if `-O` is used.

2024-06-27 21:47 UTC, heifner commented
> So we probably shouldn't use assert as the wait will not be executed if `-O` is used.

We use assert in many integration tests. If you think that, then should create an issue to update all of them.

2024-06-27 21:56 UTC, greg7mdp commented
> We use assert in many integration tests. If you think that, then should create an issue to update all of them.

fair enough, will do.

2024-06-28 11:20 UTC, greg7mdp approved these changes

2024-06-28 11:29 UTC, merged

2024-06-28 16:52 UTC, ericpassmore commented
Note:start
group: STABILITY
category: TEST
summary: Improve measurement of sync by waiting for begin block.
Note:end