SHiP finality_data: use string encoding of public keys in pending finalizer policy
AntelopeIO/spring pull request #348
Opened 2024-07-10 15:17 UTC by linh2931

For simpler and easier uses by SHiP clients, use string encoded public keys of pending finalizer policy in finality_data. It is decided both on-disk SHiP logs and websocket streaming use the same string format, for keeping consistent with other data in SHiP (disk and wire formats are the same), and for simpler implementation.

`ship_protocol.hpp` in abieos submodule will be updated after this PR is merged.

Resolves https://github.com/AntelopeIO/spring/issues/342.

2024-07-10 18:27 UTC, heifner requested changes

2024-07-10 18:27 UTC, heifner commented on libraries/chain/include/eosio/chain/finality/finalizer_authority.hpp
> +      finalizer_authority_with_string_key(const finalizer_authority& input)
Make `explicit`

2024-07-10 18:27 UTC, heifner commented on libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp
> +      finalizer_policy_with_string_key(const finalizer_policy& input)
Make `excplicit`

2024-07-10 19:00 UTC, spoonincode approved these changes

2024-07-10 19:11 UTC, greg7mdp approved these changes

2024-07-10 19:51 UTC, linh2931 commented on libraries/chain/include/eosio/chain/finality/finalizer_authority.hpp
> +      finalizer_authority_with_string_key(const finalizer_authority& input)
https://github.com/AntelopeIO/spring/pull/348/commits/64b30a41ae1c103c367d648cb5b0073573d6a222

2024-07-10 19:51 UTC, linh2931 commented on libraries/chain/include/eosio/chain/finality/finalizer_policy.hpp
> +      finalizer_policy_with_string_key(const finalizer_policy& input)
https://github.com/AntelopeIO/spring/pull/348/commits/64b30a41ae1c103c367d648cb5b0073573d6a222

2024-07-10 20:01 UTC, heifner approved these changes

2024-07-10 20:31 UTC, merged

2024-07-15 17:35 UTC, ericpassmore commented
Note:start
group: STABILITY
category: INTERNALS
summary: To support ease of use SHiP, finality_data captures a new pending finality policy, including encoded public keys from pending finality data.
Note:end