progress logging during snapshot creation
AntelopeIO/spring pull request #457
Opened 2024-08-01 16:24 UTC by spoonincode

Add status and progress logs during snapshot creation; can look something like
```
info  2024-08-01T16:18:01.831 nodeos    controller.cpp:3525           log_applied          ] Received block 84115323a9ceb11e... #386613117 @ 2024-08-01T16:18:02.000 signed by eoscannonchn [trxs: 20, lib: 386612788, net: 3016, cpu: 16896, elapsed: 2885, time: 6155, latency: -168 ms]
info  2024-08-01T16:18:01.976 nodeos    snapshot_scheduler.cpp:219    create_snapshot      ] Starting snapshot creation at block 386613117
info  2024-08-01T16:18:06.024 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 10% complete
info  2024-08-01T16:18:11.008 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 16% complete
info  2024-08-01T16:18:16.021 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 27% complete
info  2024-08-01T16:18:21.014 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 35% complete
info  2024-08-01T16:18:26.020 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 47% complete
info  2024-08-01T16:18:31.030 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 53% complete
info  2024-08-01T16:18:36.022 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 61% complete
info  2024-08-01T16:18:41.008 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 80% complete
info  2024-08-01T16:18:46.013 nodeos    snapshot.hpp:431              progress             ] Snapshot creation 87% complete
info  2024-08-01T16:18:49.210 nodeos    snapshot_scheduler.cpp:228    create_snapshot      ] Snapshot creation at block 386613117 complete; snapshot will be available once block becomes irreversible
info  2024-08-01T16:19:19.339 nodeos    controller.cpp:3525           log_applied          ] Received block dfc6827a3b3cec00... #386613118 @ 2024-08-01T16:18:02.500 signed by eoscannonchn [trxs: 15, lib: 386612788, net: 4408, cpu: 14767, elapsed: 5143, time: 12016, latency: 76839 ms]
...
info  2024-08-01T16:20:47.085 nodeos    controller.cpp:3525           log_applied          ] Received block 590e9cb5752b3afb... #386613448 @ 2024-08-01T16:20:47.500 signed by eoslaomaocom [trxs: 28, lib: 386613112, net: 6200, cpu: 15072, elapsed: 7637, time: 16368, latency: -414 ms]
info  2024-08-01T16:20:47.994 nodeos    pending_snapshot.hpp:54       finalize             ] Snapshot created at block 386613117 available as file snapshot-170b3f7d84115323a9ceb11efbe837517fb129bb019e1c0c2b131b7a1a041026.bin
info  2024-08-01T16:20:47.997 nodeos    controller.cpp:3525           log_applied          ] Received block 5421f3049893c12d... #386613449 @ 2024-08-01T16:20:48.000 signed by eosnationftw [trxs: 35, lib: 386613124, net: 8224, cpu: 9747, elapsed: 5038, time: 10782, latency: -2 ms]
```

Resolves AntelopeIO/leap#1166

2024-08-01 16:50 UTC, heifner requested changes

2024-08-01 16:50 UTC, heifner commented on libraries/chain/include/eosio/chain/pending_snapshot.hpp
> +      ilog("Snapshot created at block ${bn} available as file ${fn}", ("bn", block_ptr->block_num())("fn", fs::path(final_path).filename()));
Seems would be better to log the full path with filename, not just the filename.

2024-08-01 18:16 UTC, heifner approved these changes

2024-08-01 19:00 UTC, greg7mdp approved these changes

2024-08-01 19:32 UTC, merged

2024-08-05 19:01 UTC, ericpassmore commented
Note:start
group: LOGGING
category: INTERNALS
summary: Progress logging during snapshot creation.
Note: end