Update API docs for new get_finalizers_info_rpc
AntelopeIO/spring pull request #460
Opened 2024-08-01 16:49 UTC by ericpassmore

Adds description for return type of new `get_finalizers_info` endpoint in `chain_api` plugin

2024-08-01 16:56 UTC, heifner requested changes

2024-08-01 16:56 UTC, heifner commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                    description: Variant type, an array of strings with the current finalizers
I think I would remove `Variant type, ` that is an implementation detail. The JSON is an object with `generation`, `threshold`, and an array of `finalizers`. Seems like that all should be described.
```
 "active_finalizer_policy": {
      "generation": 1,
      "threshold": 3,
      "finalizers": [
        {
          "description": "finalizer #1",
          "weight": 1,
          "public_key": "PUB_BLS_PcJG7lYgwZcsFGe-i4WWYDw1GtP7r5vGWFcRe97TVcp5f5_h6RRRPRhZSGKtRF4CtdJxAP50VewH4VIhMIPfhsu9C4GGH4MgOzSwl51N3EK6XiAiRHQ_lcGvxggipYwIReHkhQ"
        },
```

2024-08-01 17:44 UTC, heifner commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                    description: List of current finalizers
List of pending finalizers

2024-08-01 17:48 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                    description: Record of last votes for top 21 finalizers
Not top 21 finalizers. We return the last votes for the finalizers in current active finalizer policy and pending finalizer policy.

2024-08-01 20:19 UTC, ericpassmore commented
Moving Out of Draft 

Updated on Staging 
https://staging.docs.eosnetwork.com/apis/spring/latest/chain.api/#operation/get_block_info

![Screenshot 2024-08-01 at 1 06 24 PM](https://github.com/user-attachments/assets/d33c5ad6-b21d-4d3a-bad3-7144f5632022)

2024-08-01 20:36 UTC, heifner approved these changes

2024-08-01 21:53 UTC, linh2931 requested changes

2024-08-01 21:53 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +  /get_finalizer_info_result:
should be `/get_finalizer_info:`

2024-08-01 21:53 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +      operationId: get_finalizer_info_result
`get_finalizer_info`

2024-08-01 21:53 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                              description: Name of finalizer, typicaly a producer acount
`typically` not `typicaly`, `account` not `acount`?

2024-08-01 21:53 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                              description: Name of finalizer, typicaly a producer acount
`typically`, `acount`

2024-08-01 21:53 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                          example: 1234
Examples of `voted_block_id` and `voted_block_num` are reverted.

2024-08-01 22:22 UTC, greg7mdp approved these changes

2024-08-01 22:22 UTC, greg7mdp commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                        description: version number of finalizers set
generation number of finalizer policy. Activated finalizer policy generation numbers are always increasing, but may have gaps.

2024-08-02 12:35 UTC, linh2931 reviewed
The several field names have been changed by the committed version of https://github.com/AntelopeIO/spring/pull/453:

`voted_policy_generation` -> finalizer_policy_generation`
`voted_block_id` -> `voted_for_block_id`
`voted_block_num` -> `voted_for_block_num`
`voted_block_timestamp` -> `voted_for_block_timestamp`

Please update the document accordingly.

2024-08-02 21:22 UTC, ericpassmore commented
@linh2931 Updated PR and updated on Staging Docs Server.

2024-08-02 21:23 UTC, ericpassmore commented
![Screenshot 2024-08-02 at 2 23 31 PM](https://github.com/user-attachments/assets/f7d403e3-a6c9-4fd5-a4e6-7fd4d88a1c46)

2024-08-03 02:49 UTC, linh2931 commented on plugins/chain_api_plugin/chain.swagger.yaml
> +                        public_key:
`description` is now the first field, `public_key` is the second. The order of the rest is correct.

2024-08-05 14:41 UTC, linh2931 approved these changes

2024-08-05 18:13 UTC, merged

2024-08-05 19:21 UTC, ericpassmore commented
Note:start
group: RELEASE
category: CHORE
summary: API docs on get_finalizer_info_rpc.
Note:end