[1.0] Pause production when max-reversible-blocks reached
AntelopeIO/spring pull request #652
Opened 2024-08-27 13:10 UTC by heifner

Change the behavior of `max-reversible-blocks`. Instead of shutting down a node when `max-reversible-blocks` is reached; pause production. 
* A node will no longer shutdown when it reaches `max-reversible-blocks`. 
* A block production node will not produce additional blocks when `max-reversible-blocks` is reached.

A block production node will report an `error`: `Not producing block because max-reversible-blocks ${m} reached, head ${h}, lib ${l}.` and will instead speculatively execute transactions until LIB advances. Note LIB can advance by finalizers being restored and other block producers producing blocks. Once the number of reversible blocks is reduced on the network, the block producer will un-pause and start producing blocks again. 

If all block producers have the same default value for `max-reversible-blocks` (3600) then after approximately 30 minutes of LIB not advancing, all block producers will pause production. Manual restart of at least one block producer will be required at that point, after finality issues have been resolved, with a higher `max-reversible-blocks`. Once a block producer with network finalizers are able to advance finality the number of reversible blocks should be reduced back down to ~2 and all other block producers will automatically un-pause and begin producing again.

Resolves #641

2024-08-27 14:37 UTC, greg7mdp approved these changes

2024-08-27 14:37 UTC, greg7mdp commented on plugins/producer_plugin/producer_plugin.cpp
> +   block_num_type             head_block_num    = head.block_num();
detail, I think it would be nicer to define `head` in the if condition where it is used, instead of so much earlier.

2024-08-27 14:45 UTC, linh2931 commented on plugins/producer_plugin/producer_plugin.cpp
> +   } else if (head_block_num - head.irreversible_blocknum() >= _max_reversible_blocks) {
Should `>=` be `>` as the option description says beyond?

2024-08-27 14:47 UTC, linh2931 requested changes

2024-08-27 14:47 UTC, linh2931 commented on plugins/producer_plugin/producer_plugin.cpp
> +   } else if (head_block_num - head.irreversible_blocknum() >= _max_reversible_blocks) {
Need to check `_max_reversible_blocks` not 0. Otherwise always pause.

2024-08-27 15:52 UTC, linh2931 approved these changes

2024-08-27 16:55 UTC, merged

2024-08-27 17:23 UTC, greg7mdp commented on plugins/producer_plugin/producer_plugin.cpp
> +   block_num_type             head_block_num    = head.block_num();
I was thinking moving just `block_handle head = chain.head();`, but never mind that is not nicer.

2024-08-29 11:39 UTC, ericpassmore commented
Note:start
group: STABILITY
category: INTERNALS
summary: Change behavior to pause production when max-reversible-blocks are reached.
Note:end