[1.0.2] SHiP: Fix hang on shutdown
AntelopeIO/spring pull request #816
Opened 2024-09-24 16:27 UTC by heifner

`state_history_plugin` (SHiP) would sometimes hang on shutdown. The `nodeos` process would get stuck trying to lock a mutex of the main application `io_context` strand while destroying a `boost::beast::websocket::stream`. 

Created a test that reproduces the failure (thanks @taokayan for #813). The failure was not reliably repeatable, but it did fail on every CI/CD run for at least one of the platforms. See for example: https://github.com/AntelopeIO/spring/actions/runs/11017331583/job/30595880305

Modified SHiP `boost::beast::websocket` to use the SHiP thread instead of the main application thread executor strand.

Resolves #815

2024-09-24 16:56 UTC, ericpassmore commented
Note:start
category: Other
component: SHiP
summary: Fix hang on shutdown.
Note:end

2024-09-24 17:10 UTC, spoonincode requested changes
> Modified SHiP `boost::beast::websocket` to use the SHiP thread instead of the main application thread executor strand

I think really what this changes is what I'd call the "default executor" of the websocket (I am not sure what the proper terminology is). My understanding was that the default executor was never used based on how the code is structured because the bound executor for every async call on the websocket was a `use_awaitable`, and that will use the coroutine's executor (which is the strand created from ship thread, in this case). The websocket certainly uses the ship thread and strand prior to this change. But if this does fix the problem there must be some other case where the default executor matters. And I do think it's good to make the default executor match up.

2024-09-24 17:16 UTC, heifner commented on plugins/state_history_plugin/state_history_plugin.cpp
> +      fc::create_listener<Protocol>(thread_pool.get_executor(), _log, accept_timeout, address, "", [this](Protocol::socket&& socket) {
In this case there is only one SHiP thread and its implicit strand. I agree that it would be better if `fc::create_listener` took a strand.

2024-09-24 17:31 UTC, spoonincode commented on plugins/state_history_plugin/state_history_plugin.cpp
> +      fc::create_listener<Protocol>(thread_pool.get_executor(), _log, accept_timeout, address, "", [this](Protocol::socket&& socket) {
Yeah for 1.0.x that's fine but we should really get it right on main -- the code is currently structured with the assumption that increasing ship threads 'just works'

2024-09-24 17:47 UTC, linh2931 commented on tests/ship_kill_client_test.py
> +args = TestHelper.parse_args({"--activate-if","--dump-error-details","--keep-logs","-v","--leave-running","--unshared"}, applicationSpecificArgs=appArgs)
I think we can start to make new tests run only under Savanna so we don't need to change again when testing under Legacy is removed. So `--activate-if` is not needed; just start the cluster using `activateIF=True`.

2024-09-24 17:47 UTC, linh2931 commented on tests/ship_kill_client_test.py
> +        start = time.perf_counter()
This `start` is not used.

2024-09-24 17:47 UTC, linh2931 commented on tests/ship_kill_client_test.py
> +totalProducerNodes=2
Why do we need 2 producer nodes?

2024-09-24 17:47 UTC, linh2931 commented on tests/ship_kill_client_test.py
> +    nonprodNode = cluster.getNode(1)
should this be prodNode1?

2024-09-24 17:55 UTC, spoonincode commented on plugins/state_history_plugin/state_history_plugin.cpp
> +               connections.emplace(new session(std::move(socket), std::move(strand), chain_plug->chain(),
The changes here seem to make only a single strand for all connections. And then this single strand is moved here? Doesn't look right. I think what you had before was better even though it still didn't make the websocket's default executor be a strand.

2024-09-24 17:57 UTC, heifner commented on plugins/state_history_plugin/state_history_plugin.cpp
> +      fc::create_listener<Protocol>(thread_pool.get_executor(), _log, accept_timeout, address, "", [this](Protocol::socket&& socket) {
Seems passing a strand works.

2024-09-24 17:59 UTC, heifner commented on tests/ship_kill_client_test.py
> +totalProducerNodes=2
We don't, updated.

2024-09-24 17:59 UTC, heifner commented on tests/ship_kill_client_test.py
> +    nonprodNode = cluster.getNode(1)
Changed to have two non-producer nodes.

2024-09-24 20:02 UTC, spoonincode approved these changes

2024-09-24 20:07 UTC, linh2931 approved these changes

2024-09-24 20:08 UTC, merged

2024-09-25 06:52 UTC, spoonincode commented on plugins/state_history_plugin/state_history_plugin.cpp
> +         boost::asio::post(app().get_io_service(), [this, socket{std::move(socket)}]() mutable {
Thinking about this more, I think this creates a (fantastically remote) possibility of the socket being destroyed after its executor is destroyed. This occurs when this callback is `post()`ed after the main thread is stopped, and then the plugin is destroyed, and then appbase is destroyed which will destroy pending callbacks. Obviously something we can tolerate for 1.0.x but another good reason to improve `create_listener`