Replace `static_cast` of forwarding references with `std::forward`
AntelopeIO/spring pull request #967
Opened 2024-10-22 18:28 UTC by greg7mdp

When stepping through eos-vm code, I noticed some incorrect `static_cast` and `std::move` usages, which don't seem to hide bugs because these functions are called with references which are afterwards unused. Still this seems worthwhile fixing imo.

2024-10-22 22:24 UTC, heifner requested changes
Need an eos-vm PR for the eos-vm changes.

2024-10-23 00:12 UTC, greg7mdp commented
> Need an eos-vm PR for the eos-vm changes.

Yes, thanks. https://github.com/AntelopeIO/eos-vm/pull/27

2024-10-23 11:21 UTC, heifner approved these changes

2024-10-23 13:19 UTC, linh2931 approved these changes

2024-10-23 14:49 UTC, merged

2024-10-25 23:18 UTC, ericpassmore commented
Note:start
category: System Stability
component: Internal
summary: Replace `static_cast` of forwarding references with `std::forward`.
Note:end